__author__ = 'rob'
from collections import Counter

text = "ACGTTGCATGTCGCATGATGCATGAGAGCT"
text2 = "CGGAAGCGAGATTCGCGTGGCGTGATTCCGGCGGGCGTGGAGAAGCGAGATTCATTCAAGCCGGGAGGCGTGGCGTGGCGTGGCGTGCGGATTCAAGCCGGCGGGCGTGATTCGAGCGGCGGATTCGAGATTCCGGGCGTGCGGGCGTGAAGCGCGTGGAGGAGGCGTGGCGTGCGGGAGGAGAAGCGAGAAGCCGGATTCAAGCAAGCATTCCGGCGGGAGATTCGCGTGGAGGCGTGGAGGCGTGGAGGCGTGCGGCGGGAGATTCAAGCCGGATTCGCGTGGAGAAGCGAGAAGCGCGTGCGGAAGCGAGGAGGAGAAGCATTCGCGTGATTCCGGGAGATTCAAGCATTCGCGTGCGGCGGGAGATTCAAGCGAGGAGGCGTGAAGCAAGCAAGCAAGCGCGTGGCGTGCGGCGGGAGAAGCAAGCGCGTGATTCGAGCGGGCGTGCGGAAGCGAGCGG"
text3 = "CTTTACTTTAAGGCGTTACTTAGTGCACAGTTTGTATACAGGTATACAGGTATACAGAGGCGTAGGCGTGCACAGTTTCTTTAGCACAGTTTGCACAGTTTAGGCGTTACTTAGTGTATACAGCTTTAAGGCGTTACTTAGTCTTTACTTTAGCACAGTTTGTATACAGGCACAGTTTCTTTAAGGCGTGTATACAGGTATACAGCTTTACTTTATACTTAGTTACTTAGTCTTTAGCACAGTTTCTTTAGCACAGTTTTACTTAGTCTTTAGTATACAGGCACAGTTTGTATACAGGCACAGTTTCTTTAGTATACAGCTTTAGTATACAGGTATACAGGCACAGTTTGTATACAGGTATACAGAGGCGTGTATACAGCTTTAGCACAGTTTTACTTAGTTACTTAGTTACTTAGTGTATACAGTACTTAGTGTATACAGTACTTAGTGCACAGTTTGCACAGTTTCTTTACTTTAAGGCGTGTATACAGCTTTACTTTACTTTATACTTAGTGTATACAGAGGCGTCTTTATACTTAGTGTATACAGGCACAGTTTAGGCGTCTTTAGCACAGTTTAGGCGTTACTTAGTCTTTACTTTAGCACAGTTTGTATACAGAGGCGTAGGCGTAGGCGTGCACAGTTTGCACAGTTTAGGCGTGTATACAGGTATACAGCTTTAGCACAGTTTAGGCGTGTATACAGCTTTAGCACAGTTTGTATACAGAGGCGTAGGCGTTACTTAGTGTATACAGGTATACAGAGGCGTTACTTAGTCTTTAGCACAGTTTTACTTAGTAGGCGTTACTTAGTTACTTAGTAGGCGTGCACAGTTTGCACAGTTTTACTTAGTGTATACAGAGGCGTAGGCGTTACTTAGT"

# Counter
# length


def find_frequent_words(sequence, length):
    counter = Counter()
    position = 0
    while position < (len(sequence) - length):
        nmer = sequence[position:position+length]
        counter[nmer] += 1
        position += 1
    return counter



cnt = find_frequent_words(text3, 11)

highest_frequency = cnt.most_common(1)[0][1]
sorted_cnt = sorted(cnt, key=cnt.get, reverse=True)

print("All n-mers: " + str(sorted_cnt))
highest_ones = []
for item in sorted_cnt:
    if cnt[item] < highest_frequency:
        break
    highest_ones.append(item)

print("Matching n-mers: " + " ".join(sorted(highest_ones)))